Fixed NPE on Linux.
java.util.concurrent.ExecutionException:
org.apache.commons.codec.EncoderException: Cannot encode Whirlpool
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
        at it.albertus.acodec.console.CodecConsole.processFile(CodecConsole.java:109)
        at it.albertus.acodec.console.CodecConsole.run(CodecConsole.java:91)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
        at picocli.CommandLine.access$1100(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at it.albertus.acodec.console.CodecConsole.main(CodecConsole.java:75)
        at it.albertus.acodec.ACodec.main(ACodec.java:18)
Caused by: org.apache.commons.codec.EncoderException: Cannot encode
Whirlpool
        at it.albertus.acodec.engine.ProcessFileTask.encode(ProcessFileTask.java:136)
        at it.albertus.acodec.engine.ProcessFileTask.run(ProcessFileTask.java:68)
        at it.albertus.acodec.console.ProcessFileRunnable.run(ProcessFileRunnable.java:29)
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
        at it.albertus.acodec.engine.ProcessFileTask.buildFileName(ProcessFileTask.java:234)
        at it.albertus.acodec.engine.ProcessFileTask.buildHashFileContent(ProcessFileTask.java:226)
        at it.albertus.acodec.engine.ProcessFileTask.encode(ProcessFileTask.java:129)
        ... 8 more